// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdbRiaHovz9qt-GaqN7Juvz-AKRLna1Kg',
    appId: '1:424444605086:web:f9eb394fdf5b0f06ed418f',
    messagingSenderId: '424444605086',
    projectId: 'zerowaste-b0d3f',
    authDomain: 'zerowaste-b0d3f.firebaseapp.com',
    storageBucket: 'zerowaste-b0d3f.firebasestorage.app',
    measurementId: 'G-4EFJ9H249W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsw3K-ejpYuUtl7A1NtDQRjmhyE2wj93U',
    appId: '1:424444605086:android:e51994bbc583f92fed418f',
    messagingSenderId: '424444605086',
    projectId: 'zerowaste-b0d3f',
    storageBucket: 'zerowaste-b0d3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4EUjH9jpZL2C1fqXh_zQ0CXFTGzdl868',
    appId: '1:424444605086:ios:bdf358fe8693d8b2ed418f',
    messagingSenderId: '424444605086',
    projectId: 'zerowaste-b0d3f',
    storageBucket: 'zerowaste-b0d3f.firebasestorage.app',
    iosBundleId: 'com.example.zero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4EUjH9jpZL2C1fqXh_zQ0CXFTGzdl868',
    appId: '1:424444605086:ios:bdf358fe8693d8b2ed418f',
    messagingSenderId: '424444605086',
    projectId: 'zerowaste-b0d3f',
    storageBucket: 'zerowaste-b0d3f.firebasestorage.app',
    iosBundleId: 'com.example.zero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdbRiaHovz9qt-GaqN7Juvz-AKRLna1Kg',
    appId: '1:424444605086:web:009d3d21b1f8cbd6ed418f',
    messagingSenderId: '424444605086',
    projectId: 'zerowaste-b0d3f',
    authDomain: 'zerowaste-b0d3f.firebaseapp.com',
    storageBucket: 'zerowaste-b0d3f.firebasestorage.app',
    measurementId: 'G-ZG3DWVB5SQ',
  );

}